layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
 
  - name: JavaScript
    web_rl: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: TypeScript
    web_rl: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/typescript/typescript.png
